### ISSUE TITLE
Hexo-NexT主题修改页面透明度及页面颜色 | Moshi

### ISSUE THREAD

**Issue by MoshiYeap** [MoshiYeap/hexo_stable_comments#17]
https://liujunzhou.cn/2018/8/16/page-background/#more 

 由于NexT主题默认的背景是不透明的，如果我们设置的有canvas_nest和canvas_three等3D动画效果，则会被文章界面遮住，本文主要讲述如何修改Hexo站点的页面透明度。

**Comment by a2396837** [comment]
喜欢这个评论

**Comment by moshiyeap** [comment]
> 喜欢这个评论

Gitalk

**Comment by ashijiu** [comment]
博主大大你好，我按照你的步骤修改了，左侧的导航栏和个人栏变透明了，但是文章和文章详情并不会透明。

**Comment by moshiyeap** [comment]
> @ashijiu
> 博主大大你好，我按照你的步骤修改了，左侧的导航栏和个人栏变透明了，但是文章和文章详情并不会透明。我看了一下应该是css\_schemes\Gemini下的index.styl中的post&comment修改的，但是还是没有成功

请问你使用的是NexT的Gemini主题吗？

**Comment by ashijiu** [comment]
> @moshiyeap
> > @ashijiu
> > 博主大大你好，我按照你的步骤修改了，左侧的导航栏和个人栏变透明了，但是文章和文章详情并不会透明。我看了一下应该是css\_schemes\Gemini下的index.styl中的post&comment修改的，但是还是没有成功
> 
> 请问你使用的是NexT的Gemini主题吗,如果是修改这段代码就可以了，也有可能你的背景是白的，所以上看去是不透明，可以加个canvas_nest动态背景试试。
> ```diff
> // Post & Comments blocks.
> .post-block {
>   padding: $content-desktop-padding;
> - background: white;
> + background: rgba(255,255,255,0.7);
>   box-shadow: $box-shadow-inner;
>   border-radius: $border-radius-inner;
> }
> ```

我使用的是scheme: Pisces主题

**Comment by moshiyeap** [comment]
> : Pisces主

改成Gemini试试看，时间久了我也记不太清楚了 不过应该就是这个配置

**Comment by moshiyeap** [comment]
> @ashijiu
> > @moshiyeap
> > > @ashijiu
> > > 博主大大你好，我按照你的步骤修改了，左侧的导航栏和个人栏变透明了，但是文章和文章详情并不会透明。我看了一下应该是css\_schemes\Gemini下的index.styl中的post&comment修改的，但是还是没有成功
> > 
> > 请问你使用的是NexT的Gemini主题吗,如果是修改这段代码就可以了，也有可能你的背景是白的，所以上看去是不透明，可以加个canvas_nest动态背景试试。
> > ```diff
> > // Post & Comments blocks.
> > .post-block {
> >   padding: $content-desktop-padding;
> > - background: white;
> > + background: rgba(255,255,255,0.7);
> >   box-shadow: $box-shadow-inner;
> >   border-radius: $border-radius-inner;
> > }
> > ```
> 
> 我使用的是scheme: Pisces主题

改成Gemini试试看，时间久了我也记不太清楚了 不过应该就是这个配置

**Comment by ashijiu** [comment]
> @moshiyeap
> > @ashijiu
> > > @moshiyeap
> > > > @ashijiu
> > > > 博主大大你好，我按照你的步骤修改了，左侧的导航栏和个人栏变透明了，但是文章和文章详情并不会透明。我看了一下应该是css\_schemes\Gemini下的index.styl中的post&comment修改的，但是还是没有成功
> > > 
> > > 请问你使用的是NexT的Gemini主题吗,如果是修改这段代码就可以了，也有可能你的背景是白的，所以上看去是不透明，可以加个canvas_nest动态背景试试。
> > > ```diff
> > > // Post & Comments blocks.
> > > .post-block {
> > >   padding: $content-desktop-padding;
> > > - background: white;
> > > + background: rgba(255,255,255,0.7);
> > >   box-shadow: $box-shadow-inner;
> > >   border-radius: $border-radius-inner;
> > > }
> > > ```
> > 
> > 我使用的是scheme: Pisces主题
> 
> 改成Gemini试试看，时间久了我也记不太清楚了 不过应该就是这个配置

好的非常感谢，大概明白怎么配置了

**Comment by lyz05** [comment]
侧边菜单栏的标签被选中后的矩形方块还不是透明的，应该还有哪一处的代码要修改。

**Comment by moshiyeap** [comment]
> @lyz05
> 侧边菜单栏的标签被选中后的矩形方块还不是透明的，应该还有哪一处的代码要修改。

是的，等有空我再去看看，你可以先自己找一下。

**Comment by moshiyeap** [comment]
> @lyz05
> 侧边菜单栏的标签被选中后的矩形方块还不是透明的，应该还有哪一处的代码要修改。

我检查了下，是透明的呀，你具体指的是哪部分呢？

**Comment by lyz05** [comment]
> @moshiyeap
> > @lyz05
> > 侧边菜单栏的标签被选中后的矩形方块还不是透明的，应该还有哪一处的代码要修改。
> 
> 我检查了下，是透明的呀，你具体指的是哪部分呢？

图片中Home标签被选中之后会有个白色的矩形框，影响背景特效的显示，可以看到圆圈被遮挡了一半。

~（我后面觉得也无所谓了，不透明可以增强辨识度）~
![图片](https://lyz05.github.io/resources/微信截图_20181006121315.png)

**Comment by moshiyeap** [comment]
@lyz05 了解了！
