### ISSUE TITLE
一个方便快捷的超星尔雅刷课小工具 | 不爱学习的刘同学

### ISSUE THREAD

**Issue by MoshiYeap** [MoshiYeap/hexo_stable_comments#19]
https://liujunzhou.top/2018/10/6/cxmooc-tool/ 

 前言需求驱动型的刘同学，这学期作死选了三门尔雅线上课程，幸运的是他在Github上扒到一些有用的资源，好资源当然是要分享了。（实际上是他提了一个Pull Requst,然后被项目管理者Merge了，忍不住想分享给大家 ！！！大雾！逃）手动看尔雅课程是不可能手动看的，这辈子都不可能的。本文分两个部分，第一部分提供给有计算机科学/软件工程背景的同学看的（优点是可以及时拉取最新的源码构建并使用插件的新功

**Comment by cz111000** [comment]
博主可以看看这个[JAVA后台版本](https://github.com/cz111000/chaoxing/blob/master/README-zh.md)
