### ISSUE TITLE
使用Git+Hooks实现Hexo站点自动部署到CentOS服务器上 | 日常掉头发

### ISSUE THREAD

**Issue by MoshiYeap** [MoshiYeap/hexo_stable_comments#4]
https://liujunzhou.cn/2018/8/15/deployer/#more 

 Hexo可以部署在 GitHub Pages, Heroku 或其他网站上。本文主要讲述如何利用Git和Hooks将本地生成的Hexo站点在自动部署Github Pages上的同时并推送到你的腾讯云或阿里云个人服务器上。Hexo 是一个快速、简洁且高效的博客框架。Hexo 使用 Markdown（或其他渲染引擎）解析文章，在几秒内，即可利用靓丽的主题生成静态网页。Hexo.io

**Comment by moshi1998** [comment]
测试一下

**Comment by moshiyeap** [comment]
回复测试
________________________________

**Comment by Betterming** [comment]
怎样修改两边的边距啊

**Comment by moshiyeap** [comment]
> 怎样修改两边的边距啊

Gemini主题会比较窄一点吧

**Comment by iNiL0119** [comment]
部署后，部分页面404，修改的配置文件不是已经配置到.gitignore中了吗
